version: "3.8"

networks:
  whaticket:
    external: true
    name: whaticket

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=mysql
    ports:
      - ${PMA_PORT:-9000}:80
    networks:
      - whaticket
